### ISSUE TITLE
支持tvOS配合mac Surge实现在线中文字幕？

### ISSUE THREAD

**Issue by thinktip** [DualSubs/DualSubs#1]
没见用法，直接给网关添加Surge模块就可以了？

**Comment by neweva** [comment]
你需要 Surge MAC 
1. 添加模塊 
2. 開啟解密 TCP也需要開啟 
3. BoxJS 設置 
4. tvOS上添加CA證書 
剛剛試過 Apple TV+ 和 Disney+ 都可以使用官方雙字幕 HboMax 沒效果
期待大佬的更新

**Comment by thinktip** [comment]
> 你需要 Surge MAC
> 
> 1. 添加模塊
> 2. 開啟解密 TCP也需要開啟
> 3. BoxJS 設置
> 4. tvOS上添加CA證書
>    剛剛試過 Apple TV+ 和 Disney+ 都可以使用官方雙字幕 HboMax 沒效果
>    期待大佬的更新

今天看到readme了，期待更新支持hbomax了
