### ISSUE TITLE
Paramount+ google translation cannot be used

### ISSUE THREAD

**Issue by kaliche1** [DualSubs/DualSubs#6]
hello, I am watching paramount+ with dualsubs, but it can't translate subs into chinese, only english subs.
I have no idea whether it's a bug or not, hoping for your reply.Thanks a lot.

**Comment by kaliche1** [comment]
others streaming apps can work， only paramount+. 
Device：IOS/QuanX.

**Comment by VirgilClyne** [comment]
> others streaming apps can work， only paramount+.
> Device：IOS/QuanX.

Zh/En subtitle options create success?

**Comment by kaliche1** [comment]
Other apps cannot show options either, but they can normally use, only paramount+ cannot show and use.

**Comment by kaliche1** [comment]
Maybe I successfully use the other apps by fortune but my operations are not right😂?
Should I set all the apps to show subs options, then have another try?

**Comment by kaliche1** [comment]
> > others streaming apps can work， only paramount+.
> 
> > Device：IOS/QuanX.
> 
> 
> 
> Zh/En subtitle options create success?

你好，感谢回复。我还是用中文写吧，过程比较复杂😂。
boxjs设置完成后，D+，hulu等设备可以显示中英文选项，Hbo也可以硬翻译。
问题就是这个派拉蒙，今天尝试了好久，boxjs无法获取缓存，影视剧里无法显示中英文字幕选项，也不能用shortcut直接翻译（在用box的时候我关了shortcut重写的，只是之前用的是shortcut版的dualsub，也是除了派拉蒙都可以用）。
派拉蒙是美版的。
